### PR TITLE
chore(cvsb-18934): update dependencies

### PR DESCRIPTION
**Pull request by JonLazariniDD**
## Ticket title
One line description
[link to ticket number]()

## Checklist
- [ ] Code has been tested manually
- [ ] PR title includes the JIRA ticket number
- [ ] Branch is rebased against the latest develop
- [ ] Squashed commit contains the JIRA ticket number

### CODE REVIEW

**Comment by JonLazariniDD** [comment]
cordova still has a high vulnerability with lodash however this package will be updated with @ionic-enterprise when implementing auth-connect #396

**Review by bristol-mike-jones — COMMENTED** [review]
NPM audit is reporting 3 high vulns.  Are these unpatchable atm?

**Comment by JonLazariniDD** [comment]
Unfortunately this one can not be updated for now as this is cordova (8) which is used to build VTA with Xcode (10) so updating it now would break the app and become unbuildable. However for #396 we have to upgrade the build tools (cordova 9) and should fix the remaining issue when running the audit (assuming vulnerabilities are not published until we upgrade cordova).
`npm audit`
```sh
found 25 vulnerabilities (22 low, 3 moderate) in 1749 scanned packages
  run `npm audit fix` to fix 2 of them.
  10 vulnerabilities require semver-major dependency updates.
  13 vulnerabilities require manual review. See the full report for details.
  ``` 
  
  ```diff
  diff --git a/package.json b/package.json
index f3ae59e..4a070f1 100644
--- a/package.json
+++ b/package.json
@@ -115,7 +115,7 @@
     "@types/debug": "^4.1.5",
     "@types/jasmine": "^2.5.41",
     "angular2-template-loader": "^0.6.2",
-    "cordova": "^8.1.2",
+    "cordova": "^9.0.0",
     "cordova-wheel-selector-plugin": "^1.1.1",
     "html-loader": "^0.5.1",
     "husky": "^3.0.9",
@@ -186,4 +186,4 @@
       "pre-push": "npm run build && npm run test-coverage"
     }
   }
-}
\ No newline at end of file
+}
```

**Review by alleypa — APPROVED** [review]

**Review by m-ujaffer — APPROVED** [review]

**Review by bristol-mike-jones — APPROVED** [review]
LGTM

**Comment by JonLazariniDD** [comment]
superseded by 18854 ticket

**Pull request closed without merging**
